#!/usr/bin/env python3
"""Turn llvm-objdump's disassembly of the carved ELF into a Lean listing.

Writes lean/ValidateFeePayer/Disasm.lean: every instruction's address,
length and Intel-syntax text (without objdump's `# ...` and `<symbol>`
annotations). Checks.lean proves that the Lean decoder's sweep over
Image.lean, printed by Print.lean, yields the same list, so the decoder agrees
with an independent disassembler on where instructions start, how long they
are, and their operands.

Run after make-artifacts.sh:  ./disasm-to-lean.py
"""
import re, sys, pathlib

root = pathlib.Path(__file__).resolve().parent
src = root / "artifacts" / "validate_fee_payer.intel.s"
out = root / "lean" / "ValidateFeePayer" / "Disasm.lean"

line_re = re.compile(r"^ +([0-9a-f]+): ([0-9a-f]{2}(?: [0-9a-f]{2})*) *\t(.*)$")
rows = []
for line in src.read_text().splitlines():
    m = line_re.match(line)
    if m:
        addr, raw, text = m.groups()
        # Drop objdump's annotations: `# comment` and `<symbol+off>`.
        text = re.sub(r"\s*#.*$", "", text)
        text = re.sub(r"\s*<[^>]*>", "", text)
        text = " ".join(text.split("\t")).strip()
        rows.append((int(addr, 16), len(raw.split()), text))
if not rows:
    sys.exit(f"no instructions in {src}")

body = ",\n".join(f"  (0x{a:x}, {n}, \"{t}\")" for a, n, t in rows)
out.write_text(f"""-- Generated by disasm-to-lean.py from artifacts/validate_fee_payer.intel.s. Do not edit.

namespace ValidateFeePayer.Disasm

/-- (address at load base 0, length, Intel-syntax text) of every instruction, as
llvm-objdump-14 disassembles the carved ELF. -/
def listing : List (UInt64 × Nat × String) := [
{body}
]

end ValidateFeePayer.Disasm
""")
print(f"{len(rows)} instructions -> {out.relative_to(root)}")
