//! `Image.lean` for the `lean/` package: the carved regions, the panic entry
//! and the measured layout as Lean definitions. The `Region` type and loading
//! at an arbitrary base live in `ValidateFeePayer/Region.lean`.

use {
    crate::{code::Code, data::DataObject, layout::Layout},
    anyhow::{Result, bail},
    serde_json::Value,
};

pub fn module(
    source_sha256: &str,
    code: &Code,
    data: &[DataObject],
    layout: &Layout,
) -> Result<String> {
    let mut s = format!(
        "-- Generated by vfp-carve from agave-validator {source_sha256}. Do not edit.
import ValidateFeePayer.Region

namespace ValidateFeePayer.Image
"
    );
    for f in &code.functions {
        s += &region(
            f.name,
            &format!("`{}`", f.symbol),
            f.vaddr,
            f.bytes,
            &[],
            true,
        );
    }
    for o in data {
        let relocations: Vec<_> = o.relocations.iter().map(|r| (r.offset, r.value)).collect();
        s += &region(
            &o.name,
            &o.description,
            o.vaddr,
            &o.bytes,
            &relocations,
            o.read_by_code,
        );
    }

    let names = |names: Vec<&str>| names.join(", ");
    s += &format!(
        "
def functions : List Region := [{}]

def data : List Region := [{}]

/-- `{}`, not carved. -/
def panicEntry : UInt64 := {:#x}

/-! Measured on x86_64-linux with the validator's toolchain; offsets in bytes. -/
namespace Layout
",
        names(code.functions.iter().map(|f| f.name).collect()),
        names(data.iter().map(|o| o.name.as_str()).collect()),
        code.panic_entry.name,
        code.panic_entry.vaddr,
    );
    let Value::Object(layout) = serde_json::to_value(layout)? else {
        bail!("layout is not a JSON object");
    };
    for (key, value) in &layout {
        layout_defs(&mut s, key, value)?;
    }
    s += "end Layout\n\nend ValidateFeePayer.Image\n";
    Ok(s)
}

fn region(
    name: &str,
    doc: &str,
    vaddr: u64,
    bytes: &[u8],
    relocations: &[(u64, u64)],
    read: bool,
) -> String {
    let rows: Vec<String> = bytes
        .chunks(16)
        .map(|row| {
            let row: Vec<String> = row.iter().map(|b| format!("{b:#04x}")).collect();
            format!("    {}", row.join(", "))
        })
        .collect();
    let mut s = format!(
        "
/-- {doc} -/
def {name} : Region where
  name := \"{name}\"
  vaddr := {vaddr:#x}
  bytes := ⟨#[
{}
  ]⟩
",
        rows.join(",\n")
    );
    if !relocations.is_empty() {
        let relocations: Vec<String> = relocations
            .iter()
            .map(|(offset, value)| format!("{{ offset := {offset}, value := {value:#x} }}"))
            .collect();
        s += &format!("  relocations := [{}]\n", relocations.join(", "));
    }
    if !read {
        s += "  readByCode := false\n";
    }
    s
}

/// Nested JSON objects become namespaces; "0x..." leaves become `Nat` defs.
fn layout_defs(s: &mut String, key: &str, value: &Value) -> Result<()> {
    match value {
        Value::Object(fields) => {
            *s += &format!("namespace {key}\n");
            for (k, v) in fields {
                layout_defs(s, k, v)?;
            }
            *s += &format!("end {key}\n");
        }
        Value::String(hex) if hex.starts_with("0x") => *s += &format!("def {key} : Nat := {hex}\n"),
        other => bail!("unexpected layout value {key}: {other}"),
    }
    Ok(())
}
