//! `Image.lean` for the `lean/` package: the carved regions, the panic entry
//! and the measured layout as Lean definitions. The `Region` type and loading
//! at an arbitrary base live in `ValidateFeePayer/Region.lean`.
//!
//! Each region gets one kind of contents, mirroring Lean's `Region.Contents`:
//! code, a constant the code reads, or a pointer slot (whose bytes depend on
//! the load base, so only its target is recorded). An object the code only
//! takes the address of is not a region, just that address: it lies in the
//! reserved span, so reading it would fault. Anything else is an error.

use {
    crate::{code::Code, data::DataObject, elf::Relocation, layout::Layout},
    anyhow::{Context, Result, bail, ensure},
    serde_json::Value,
};

enum Contents<'a> {
    Code(&'a [u8]),
    Constant(&'a [u8]),
    Pointer(u64),
}

impl<'a> Contents<'a> {
    fn of_data(o: &'a DataObject) -> Result<Self> {
        match o.relocations[..] {
            [] => Ok(Self::Constant(&o.bytes)),
            [Relocation { offset: 0, value }] if o.bytes.len() == 8 => {
                ensure!(
                    o.bytes == value.to_le_bytes(),
                    "pointer slot bytes differ from its relocation value"
                );
                Ok(Self::Pointer(value))
            }
            _ => bail!("read object with relocated words that is not a pointer slot"),
        }
    }

    fn lean(&self) -> String {
        match self {
            Self::Code(bytes) => format!(".code {}", byte_array(bytes)),
            Self::Constant(bytes) => format!(".constant {}", byte_array(bytes)),
            Self::Pointer(target) => format!(".pointer {target:#x}"),
        }
    }
}

pub fn module(
    source_sha256: &str,
    code: &Code,
    data: &[DataObject],
    layout: &Layout,
    (reserved_start, reserved_end): (u64, u64),
) -> Result<String> {
    let mut s = format!(
        "-- Generated by vfp-carve from agave-validator {source_sha256}. Do not edit.
import ValidateFeePayer.Region

namespace ValidateFeePayer.Image
"
    );
    for f in &code.functions {
        let contents = Contents::Code(f.bytes);
        s += &region(f.name, &format!("`{}`", f.symbol), f.vaddr, &contents);
    }
    let (read, address_only): (Vec<_>, Vec<_>) = data.iter().partition(|o| o.read_by_code);
    for o in &read {
        let contents = Contents::of_data(o).with_context(|| o.name.clone())?;
        s += &region(&o.name, &o.description, o.vaddr, &contents);
    }
    for o in &address_only {
        s += &format!(
            "\n/-- {} -/\ndef {} : ImageOffset := {:#x}\n",
            o.description, o.name, o.vaddr
        );
    }

    let names = |names: Vec<&str>| names.join(", ");
    s += &format!(
        "
def functions : List Region := [{}]

def data : List Region := [{}]

def regions : List Region := functions ++ data

/-- From the lowest `p_vaddr` to the highest `p_vaddr + p_memsz` of the source
binary's `PT_LOAD` segments. -/
def reservedStart : ImageOffset := {:#x}
def reservedEnd : Nat := {:#x}

/-- `{}`, not carved. -/
def panicEntry : ImageOffset := {:#x}

/-! Measured on x86_64-linux with the validator's toolchain; offsets in bytes. -/
namespace Layout
",
        names(code.functions.iter().map(|f| f.name).collect()),
        names(read.iter().map(|o| o.name.as_str()).collect()),
        reserved_start,
        reserved_end,
        code.panic_entry.name,
        code.panic_entry.vaddr,
    );
    let Value::Object(layout) = serde_json::to_value(layout)? else {
        bail!("layout is not a JSON object");
    };
    for (key, value) in &layout {
        layout_defs(&mut s, key, value)?;
    }
    s += "end Layout\n\nend ValidateFeePayer.Image\n";
    Ok(s)
}

fn region(name: &str, doc: &str, vaddr: u64, contents: &Contents) -> String {
    format!(
        "
/-- {doc} -/
def {name} : Region where
  name := \"{name}\"
  address := {vaddr:#x}
  contents := {}
",
        contents.lean()
    )
}

fn byte_array(bytes: &[u8]) -> String {
    let rows: Vec<String> = bytes
        .chunks(16)
        .map(|row| {
            let row: Vec<String> = row.iter().map(|b| format!("{b:#04x}")).collect();
            format!("    {}", row.join(", "))
        })
        .collect();
    format!("⟨#[\n{}\n  ]⟩", rows.join(",\n"))
}

/// Nested JSON objects become namespaces; "0x..." leaves become `Nat` defs.
fn layout_defs(s: &mut String, key: &str, value: &Value) -> Result<()> {
    match value {
        Value::Object(fields) => {
            *s += &format!("namespace {key}\n");
            for (k, v) in fields {
                layout_defs(s, k, v)?;
            }
            *s += &format!("end {key}\n");
        }
        Value::String(hex) if hex.starts_with("0x") => *s += &format!("def {key} : Nat := {hex}\n"),
        other => bail!("unexpected layout value {key}: {other}"),
    }
    Ok(())
}
