//! Assembler source and linker script for `validate_fee_payer.elf`: the carved
//! code and data at their original addresses, and nothing else.
//!
//! Each piece gets its own section and `PT_LOAD` segment, so the gaps between
//! them (megabytes, in places) are not filled into the file. Mangled symbol
//! names are left out; they are in the manifest.

use crate::{code::Code, data::DataObject};

const PF_X: u32 = 1;
const PF_R: u32 = 4;

pub fn assembly(code: &Code, data: &[DataObject]) -> String {
    let mut s =
        String::from("# Generated by vfp-carve.\n\t.section .note.GNU-stack,\"\",@progbits\n");
    for f in &code.functions {
        let name = f.name;
        s += &format!(
            "
\t.section .text.{name},\"ax\",@progbits
\t.globl {name}
\t.type {name},@function
\t.size {name}, {size:#x}
{name}:
\t.incbin \"{name}.bin\"
",
            size = f.bytes.len()
        );
    }
    for o in data {
        let name = &o.name;
        let bytes: Vec<String> = o.bytes.iter().map(|b| format!("{b:#04x}")).collect();
        s += &format!(
            "
\t.section .rodata.{name},\"a\",@progbits
\t.globl {name}
\t.type {name},@object
\t.size {name}, {size:#x}
{name}:
\t.byte {bytes}
",
            size = o.bytes.len(),
            bytes = bytes.join(", ")
        );
    }
    s
}

pub fn linker_script(code: &Code, data: &[DataObject]) -> String {
    let functions = code
        .functions
        .iter()
        .map(|f| (f.vaddr, format!(".text.{}", f.name), PF_R | PF_X));
    let objects = data
        .iter()
        .map(|o| (o.vaddr, format!(".rodata.{}", o.name), PF_R));
    let mut pieces: Vec<_> = functions.chain(objects).collect();
    pieces.sort();

    let phdrs: String = pieces
        .iter()
        .enumerate()
        .map(|(i, (_, _, flags))| format!("  seg{i} PT_LOAD FLAGS({flags});\n"))
        .collect();
    let sections: String = pieces
        .iter()
        .enumerate()
        .map(|(i, (vaddr, section, _))| {
            format!("  {section} {vaddr:#x} : {{ KEEP(*({section})) }} :seg{i}\n")
        })
        .collect();
    format!(
        "/* Generated by vfp-carve. */
ENTRY(validate_fee_payer)

PHDRS
{{
{phdrs}}}

SECTIONS
{{
{sections}  /DISCARD/ : {{ *(.note*) *(.comment) *(.eh_frame*) }}
}}

/* {panic}: not carved; reaching it means the function panicked. */
expect_failed = {panic_vaddr:#x};
",
        panic = code.panic_entry.name,
        panic_vaddr = code.panic_entry.vaddr,
    )
}
